### ISSUE TITLE
Error when build with product

### ISSUE THREAD

**Issue by docaohuynh** [Jam3/angular-components-library#3]
Dear Team!
I has an error when build with ng build --prod

```
ERROR in Error during template compile of 'YTPlayerModule'
  Function calls are not supported in decorators but 'YTPlayerConfig' was called.
```
How do I solve this
Thanks

**Comment by neo** [comment]
Hi, thank you for your issue! We'll try to look into it within a day or two and let you know ASAP!

**Comment by neo** [comment]
Hi @docaohuynh! We just published `angular-youtube-player@1.0.2`, can you please try it out and let us know if it works for you?

**Comment by docaohuynh** [comment]
It worked!
Thanks for your help!

**Comment by neo** [comment]
You're very welcome!
Thank you so much for reporting the issue!
