### ISSUE TITLE
Won't compile if @types/youtube is not included in package.json

### ISSUE THREAD

**Issue by Lolmewn** [Jam3/angular-components-library#4]
Using `"angular-youtube-player": "^1.0.2"`
Specifically, the following error occurs when building the application:
```
ERROR in node_modules/angular-youtube-player/lib/ytplayer.component.d.ts(8,26): error TS2503: Cannot find namespace 'YT'.
node_modules/angular-youtube-player/lib/ytplayer.component.d.ts(1,23): error TS2688: Cannot find type definition file for 'youtube'.
```
I managed to resolve this by adding `"@types/youtube": "^0.0.35"` to my `package.json` under `devDependencies`, but since this wasn't documented anywhere I figured I should report this bug.

**Comment by neo** [comment]
thank you very much for your help!
I'll make the update accordingly.

**Comment by neo** [comment]
reference: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by neo** [comment]
It should be fixed now, thank you for your feedback!

**Comment by puneetv05** [comment]
Hey, @neo please mention types in readme file as starting with npm@3 peer dependencies will not be automatically installed. thanks for the lib (y)
