### ISSUE TITLE
when I try to update to angular 8 via ng update @angular/cli @angular/core

### ISSUE THREAD

**Issue by slavazhabitsky** [Jam3/angular-components-library#5]
Package "angular-youtube-player" has an incompatible peer dependency to "@angular/common" (requires "^6.0.0" (extended), would install "8.0.0").
                  Package "angular-youtube-player" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0" (extended), would install "8.0.0").

**Comment by neo** [comment]
Thank you for your feedback, it should still work with 8.0.0; will find a time to double check and make updates accordingly.
Meanwhile you should be able to still use it normally ignoring the npm warning, let us know if there's any problem.
Thank you again for using it and providing feedbacks!

**Comment by neo** [comment]
Closed by #8.

**Comment by neo** [comment]
It should be fixed now, thank you for your feedback!
